// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: alert.proto

package pbgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendAlertRequestClient is the client API for SendAlertRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendAlertRequestClient interface {
	SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
}

type sendAlertRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewSendAlertRequestClient(cc grpc.ClientConnInterface) SendAlertRequestClient {
	return &sendAlertRequestClient{cc}
}

func (c *sendAlertRequestClient) SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, "/alerter.SendAlertRequest/SendAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendAlertRequestServer is the server API for SendAlertRequest service.
// All implementations must embed UnimplementedSendAlertRequestServer
// for forward compatibility
type SendAlertRequestServer interface {
	SendAlert(context.Context, *AlertRequest) (*AlertResponse, error)
	mustEmbedUnimplementedSendAlertRequestServer()
}

// UnimplementedSendAlertRequestServer must be embedded to have forward compatible implementations.
type UnimplementedSendAlertRequestServer struct {
}

func (UnimplementedSendAlertRequestServer) SendAlert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAlert not implemented")
}
func (UnimplementedSendAlertRequestServer) mustEmbedUnimplementedSendAlertRequestServer() {}

// UnsafeSendAlertRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendAlertRequestServer will
// result in compilation errors.
type UnsafeSendAlertRequestServer interface {
	mustEmbedUnimplementedSendAlertRequestServer()
}

func RegisterSendAlertRequestServer(s grpc.ServiceRegistrar, srv SendAlertRequestServer) {
	s.RegisterService(&SendAlertRequest_ServiceDesc, srv)
}

func _SendAlertRequest_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAlertRequestServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alerter.SendAlertRequest/SendAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAlertRequestServer).SendAlert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendAlertRequest_ServiceDesc is the grpc.ServiceDesc for SendAlertRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendAlertRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerter.SendAlertRequest",
	HandlerType: (*SendAlertRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAlert",
			Handler:    _SendAlertRequest_SendAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alert.proto",
}
